services:
  test-main-terraform-use-cases:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TEST_SF_TF_GENERATED_RANDOM_VALUE: ${TEST_SF_TF_GENERATED_RANDOM_VALUE}
      TEST_SF_TF_TEST_OBJECT_SUFFIX: ${TEST_SF_TF_TEST_OBJECT_SUFFIX}
      TEST_SF_TF_SNOWFLAKE_TESTING_ENVIRONMENT: NON_PROD
    volumes:
      - ./../:/terraform-provider-snowflake
      - ${SNOWFLAKE_CONFIG_PATH}:/root/.snowflake/config
      - shared_data:/shared
    working_dir: /terraform-provider-snowflake
    # Run the tests and save the results to the test_output.json file
    # The piped output from `tee` is processed (using `jq` to get Output field and grep to skip empty lines) before being outputted to the console
    # pipefail is set to ensure that if any command in the pipeline fails, the entire command fails
    command: bash -c "set -o pipefail; make test-main-terraform-use-cases | tee /shared/test_output.json | jq -r --unbuffered 'select(.Output != null) | .Output | select(length > 0)' | grep -v '^$'"
  process-test-output:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./../:/terraform-provider-snowflake
      - shared_data:/shared
    command: bash -c "go run /terraform-provider-snowflake/pkg/scripts/test_output_processor/test_output_processor.go < /shared/test_output.json"

volumes:
  shared_data:
