services:
  test-main-terraform-use-cases:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TEST_SF_TF_GENERATED_RANDOM_VALUE: ${TEST_SF_TF_GENERATED_RANDOM_VALUE}
      TEST_SF_TF_TEST_OBJECT_SUFFIX: ${TEST_SF_TF_TEST_OBJECT_SUFFIX}
    volumes:
      - ./../:/terraform-provider-snowflake
      - ${SNOWFLAKE_CONFIG_PATH}:/root/.snowflake/config
      - shared_data:/shared
    working_dir: /terraform-provider-snowflake
    command: make --silent test-main-terraform-use-cases 1> /shared/test_output.json
  process-test-output:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./../:/terraform-provider-snowflake
      - shared_data:/shared
    command: go run /terraform-provider-snowflake/pkg/scripts/test_output_processor/test_output_processor.go < /shared/test_output.json

volumes:
  shared_data:
